print("Hey! \nBuddy!!! \nHow you doin...???")
print("This is auto output")
print("this will print means github is sending push triggers")
print("trhis is error")
print("this will move to remote server")
